timepad/front-components

- src/components/button/Button.tsx
- src/components/button/SliderButton.tsx
1. [new][S] Изменен способ импорта react
connects to https://timepad.myjetbrains.com/youtrack/issue/ACT-210
> Изменен способ импорта react 

- package.json
1. [ref] - Отключил правило "react/prop-types" конфиге
https://timepad.myjetbrains.com/youtrack/issue/MON-88
> Добавил хеш комита c отключенным правилом в package.json

- .eslintrc.js
1. [bfx] Добавил в конфиг проекта "front-components" прямую ссылку на правило "react/prop-types" из "front-shared"
https://timepad.myjetbrains.com/youtrack/issue/MON-89
> Поправил конфиг еслинта

- package.json
1. [bfx] Исправлен хэш для зависимости front-shared на валидный
https://timepad.myjetbrains.com/youtrack/issue/TPI-73
> Исправлен хэш для зависимости front-shared на валидный

- package.json
1. [ref] Заменён хэш пакета зависимости front-shared
https://timepad.myjetbrains.com/youtrack/issue/TPI-75
> Заменён хэш пакета зависимости front-shared

- src/components/tabs/Tab.tsx
- src/components/tabs/Tabs.tsx
1. [new] Расширены возможности кода компонента табов в UI-ките;
https://timepad.myjetbrains.com/youtrack/issue/TPI-81
> Расширены возможности кода компонента табов в UI-ките

- .github/workflows/chromatic.yml
- .github/workflows/eslint.yml
- src/components/button/Button.stories.tsx
1. [new] В UI-кит добавлен Хроматик и теперь его можно смотреть дизайнерам и тестировщикам;
https://timepad.myjetbrains.com/youtrack/issue/TPI-85
> В UI-кит добавлен Хроматик и теперь его можно смотреть дизайнерам и тестировщикам

- src/components/tabs/TabContent.tsx
1. [bfx] Исправлена опечатка в именовании класса TabBar.
https://timepad.myjetbrains.com/youtrack/issue/TPI-105
> Исправлена опечатка в именовании класса TabBar

- src/components/dropdown/Body.tsx
- src/components/dropdown/cdrop.less
1. Поправлен баг с фоном dropdown на мобильных
https://timepad.myjetbrains.com/youtrack/issue/AF-266
> AF-266 - багфикс в dropdown

- src/components/dropdown/Dropdown.tsx
- src/components/dropdown/interfaces.ts
> Откачено "Обновлен компонент выпадающего меню (dropdown) для более комфортного использования"

- src/components/userpic/Pic.tsx
- src/components/userpic/cuserpic.less
Теперь при наведении на аватарку нет белой круглой рамки вокруг Userpic, аватарка затемняется при наведении и чуть светлеет при нажатии. 
1. [bfx] Исправлен баг с бордером для аватарок с картинками
2. [ref] Отрефакторен компонент Pic.tsx - добавлены дополнительные компоненты для аватарки с картинкой и для аватарки с лейблом
3. [ref] Убрано старое поведение при наведении на аватарку, добавили новое
4. [new] Добавлено поведение при нажатии на аватарку
https://timepad.myjetbrains.com/youtrack/issue/TPI-320
> Исправлено некорректное поведение компонента Userpic в front-components при наведении на него мышкой.

- src/components/dropdown/Dropdown.tsx
- src/components/dropdown/interfaces.ts
1. [ref] Прокинуты дополнительные пропсы
https://timepad.myjetbrains.com/youtrack/issue/PL-385
> Обновлен компонент выпадающего меню (dropdown) для более комфортного использования

- src/components/accordion/Accordion.tsx
1. [bfx] Поправлен баг с закрытием аккордеона при нажатии на контент внутри него
https://timepad.myjetbrains.com/youtrack/issue/PL-490
> Поправлен баг с закрытием аккордеона при нажатии на контент

- src/components/segmentedcontrol/ControlList.tsx
- src/components/segmentedcontrol/Segmentedcontrol.stories.tsx
1. [bfx] При изменении текста контрола плашка активного контрола тоже меняется
https://timepad.myjetbrains.com/youtrack/issue/PL-504
> Добавлена обработка изменения текста контролов SegmentedControl

- src/assets/css/layout/lflex.less
1. [new] Добавлено свойство высоты во весь экран для флексовых компонентов lflex
https://timepad.myjetbrains.com/youtrack/issue/AF-347
> Добавлено свойство высоты во весь экран для флексовых компонентов

- src/assets/svg/16/icon-arrow-sorting-down-16.svg
- src/components/dropdown/interfaces.ts
1. [new] - Добавлена иконка стрелочки
https://timepad.myjetbrains.com/youtrack/issue/PL-355
> Добавлена иконка стрелочки для сортировки

- src/assets/css/otp-styles-bundle.less
- src/assets/svg/16/icon-arrow-sorting-down-16.svg
- src/components/dropdown/interfaces.ts
- src/components/form/Checkbox/Checkbox.tsx
- src/components/form/Checkbox/cform__checkbox.less
- src/components/form/Radio/Radio.tsx
- src/components/form/Radio/cform__radio.less
- src/components/typography/Typography.stories.tsx
- src/components/typography/Typography.tsx
- src/components/typography/TypographyBody.tsx
- src/components/typography/TypographyCaption.tsx
- src/components/typography/TypographyHeader.tsx
- src/components/typography/TypographyLead.tsx
- src/components/typography/TypographyMultiple.tsx
- src/components/typography/TypographySmall.tsx
- src/components/typography/TypographySubheader.tsx
- src/components/typography/ctypography.less
- src/components/typography/index.less
- src/components/typography/index.tsx
- src/index.tsx
https://timepad.myjetbrains.com/youtrack/issue/TPI-363
> Выкачены накопленные изменения

- src/components/button/Button.stories.tsx
- src/components/button/Button.tsx
- src/components/button/cbtn.less
1. [new] Добавлена возможность задавать свой цвет тексту в кнопке
https://timepad.myjetbrains.com/youtrack/issue/AF-378
> Добавлена возможность задавать свой цвет тексту в кнопке

- src/components/grid/Grid.stories.tsx
- src/components/grid/Grid.tsx
- src/components/grid/GridCol.tsx
- src/components/grid/getActualGridSize.ts
- src/components/grid/index.ts
- src/components/grid/types.ts
- src/index.tsx
1. [new] Добавлен новый компонент Grid
https://timepad.myjetbrains.com/youtrack/issue/TPI-407
> Разработан компонент Grid

- src/components/typography/Typography.stories.tsx
- src/components/typography/Typography.tsx
- src/components/typography/TypographyBody.tsx
- src/components/typography/TypographyCaption.tsx
- src/components/typography/TypographyHeader.tsx
- src/components/typography/TypographyLead.tsx
- src/components/typography/TypographyMultiple.tsx
- src/components/typography/TypographySmall.tsx
- src/components/typography/TypographySubheader.tsx
- src/components/typography/ctypography.less
1. [new] Добавлен prop: fontWeight
2. [ref] Отрефакторены пропсы, стили
https://timepad.myjetbrains.com/youtrack/issue/TPI-412
> Добавлен fontWeight для Typography

- src/components/modal/Modal.stories.tsx
- src/components/modal/cmodal.less
1. [bfx] исправлены заголовки для случая двух кнопок в заголовке
2. [new] добавлена сторис описывающая это поведение 
https://timepad.myjetbrains.com/youtrack/issue/AF-393
> Исправлены отступы в заголовке модального окна

- src/components/button/Button.tsx
1. [bfx] Исправлены прокидывания стилей к иконкам в кнопках
https://timepad.myjetbrains.com/youtrack/issue/AF-398
> Исправлено прокидывание стилей к иконкам в кнопках

- src/components/dropdown/Dropdown.tsx
- src/components/dropdown/interfaces.ts
- src/components/popup/index.tsx
1. [new] прикидываем пропс сквозь дропдаун до попапа
https://timepad.myjetbrains.com/youtrack/issue/AF-394
> Добавлен пропс для дропдаунов из необычных мест, например если дропдаун в модалке

- src/assets/css/layout/lgap.less
- src/assets/svg/24/icon-rus-rouble-24.svg
1. [ref][S]Добавлено min-width для Gap.
2. [new][S]Добавлена иконка рубля.
https://timepad.myjetbrains.com/youtrack/issue/ACT-579
> Добавлено min-width для Gap. Добавлена иконка рубля.

- Dockerfile
1. [new] Добавлен Dockerfile - влияет только на сборки в teamcity
https://timepad.myjetbrains.com/youtrack/issue/DEVOPS-474
> Docker file for deployment

- src/assets/css/otp-styles-bundle.less
1. [bfx] - Добавил файл со стилями в бандл
https://timepad.myjetbrains.com/youtrack/issue/RET-273
> Подключены стили для форм в ЛК

- src/components/popup/index.tsx
1. Поправлен ресет скролла
https://timepad.myjetbrains.com/youtrack/issue/RET-179/Otkryt-Afishu-13-Filtry
> Поправлен ресет скролла

- src/components/typography/Typography.stories.tsx
- src/components/typography/TypographyMultiple.tsx
- src/components/typography/ctypography.less
1.[ref] - edit Typography.Multiple to container
https://timepad.myjetbrains.com/youtrack/issue/RET-464/Vozrastnaya-markirovka-na-stranice-sobytij-Razrabotka
> Исправлен компонент Typography.Multiple

- src/components/divider/Divider.stories.tsx
- src/components/divider/Divider.tsx
- src/components/divider/cdivider.less
1. [new][M] Добавлена возможность добавления отступов.
2. [new][M] Добавлена возможность задания расположения.
https://timepad.myjetbrains.com/youtrack/issue/TPI-580/Komponent-Divider
> Расширение компонента Divider.

- src/components/form/TextLight/Input.tsx
- src/components/form/TextLight/PhoneInput.tsx
- src/components/form/TextLight/TextLight.tsx
- src/components/form/TextLight/TextLight.types.ts
- src/components/form/TextLight/TextLightField.tsx
- src/services/helpers/maskHelpers/convertStringMaskToRegexp.ts
- src/services/helpers/maskHelpers/fitInputValueIntoMask.ts
- src/services/helpers/maskHelpers/getFormattedPhone.ts
- src/services/helpers/maskHelpers/getMaskedValue.ts
- src/services/helpers/maskHelpers/getNewValue.ts
- src/services/helpers/maskHelpers/getNextCursorPosition.ts
- src/services/helpers/maskHelpers/getPlaceholderFromMask.ts
- src/services/helpers/maskHelpers/index.ts
- src/services/helpers/maskHelpers/setCursorPositionForElement.ts
- src/services/hooks/index.tsx
- src/services/hooks/useCallbackAfterRender.ts
- src/services/hooks/useMask.ts
1. [new][M] - В поле ввода мобильного телефона добавлена обработка вставки телефона из буфера.
https://timepad.myjetbrains.com/youtrack/issue/Dev-163/Pokazyvat-7-pri-logine-organizatora-s-business
> Добавлена возможность вставки номера из буфера обмена

- src/components/modal/Modal.tsx
- src/components/modal/ModalContent.tsx
1. [new][M] - Добавлен новый компонент в модальное окно
https://timepad.myjetbrains.com/youtrack/issue/Dev-235/Bannernye-mesta-Front-Realizovat-bannery-CheckOut-i-CheckOut-mobile
> Добавлена возможность отображения Баннера в модальном окне

- src/components/modal/Modal.stories.tsx
- src/components/modal/Modal.tsx
- src/components/modal/ModalHeader.tsx
- src/components/userpic/Pic.tsx
- src/services/helpers/extractDataAttrs/extractDataAttrs.ts
- src/services/helpers/extractDataAttrs/index.ts
https://timepad.myjetbrains.com/youtrack/issue/TPI-35/Razmetit-afishu-dlya-avtotestov-soglasno-rezultatam-risyorcha
> Разметка афиши атрибутами для написания автотестов

- src/assets/css/otp-styles-bundle.less
- src/components/form/Form/Form.tsx
- src/components/form/SearchInput/SearchInput.stories.tsx
- src/components/form/SearchInput/SearchInput.tsx
- src/components/form/SearchInput/SearchInput.types.ts
- src/components/form/SearchInput/csearch-input.less
- src/components/form/SearchInput/index.less
- src/components/form/SearchInput/index.ts
- src/services/helpers/keyPressHelper/index.ts
- src/services/helpers/keyPressHelper/keyPressHelper.ts
1. [new][M] - Добавление компонента SearchInput во FC
https://timepad.myjetbrains.com/youtrack/issue/Dev-195/Redizajn-razdela-Sobytiya-5.3.-Poisk-Front
> Добавление компонента SearchInput во Front-components

- src/services/helpers/extractDataAttrs/extractDataAttrs.ts
https://timepad.myjetbrains.com/youtrack/issue/Dev-332
> Исправляем ошибку, когда не найден ключ data-qa

- src/components/dropdown/DropDown.stories.tsx
- src/components/dropdown/Dropdown.tsx
- src/components/dropdown/cdropdown.less
- src/components/popup/index.tsx
1. [new][M] - Добавлены псевдоэлементы к компоненту Dropdown
https://timepad.myjetbrains.com/youtrack/issue/Dev-339/Pomenyat-process-pereklyucheniya-mezhdu-akkauntami-v-LK-organizatora
> Добавлен padding для Dropdown для процесса переключения между аккаунтами в ЛК организатора 

- src/components/pagination/cpagination.less
1. [ref][S] - Изменен margin-left, margin-right для стрелок в пагинации 
https://timepad.myjetbrains.com/youtrack/issue/Dev-517/Redizajn-razdela-Sobytiya-Dobavit-vozmozhnost-prolistyvat-spisok-sobytij-na-neskolko-stranic
> Добавлена возможность пролистывать список событий на несколько страниц

- src/components/modal/Modal.tsx
https://timepad.myjetbrains.com/youtrack/issue/Dev-555/Perehod-na-licenzionnye-dogovory
> Dev-555 Переход на лицензионные договора #4590

- src/components/form/TextLight/PhoneInput.tsx
- src/services/hooks/useMask.ts
1. [bfx][M] - Исправлена работа onBlur и onFocus в PhoneInput
[task](https://timepad.myjetbrains.com/youtrack/issue/Dev-449/Dobavit-validaciyu-kirillicy-v-e-mail-v-ankete-registracii-na-ER5)
> DEV-449 Добавить валидацию кириллицы в e-mail в анкете регистрации на ЕР5

- src/components/searchinput/SearchInput.stories.tsx
- src/components/searchinput/SearchInput.tsx
- src/components/searchinput/SearchInput.types.ts
- src/components/searchinput/csearch-input.less
- src/services/helpers/keyPressHelper/keyPressHelper.ts
1. [ref][M] - Изменена логика работу SearchInput
https://timepad.myjetbrains.com/youtrack/issue/Dev-369/Redizajn-Glavnaya-Afishi-1.-Shapka-front
> DEV-369 [Редизайн: Главная Афиши] 1. Шапка (front)

- src/components/dropdown/DropDown.stories.tsx
[ref] [M] В компоненте dropdown описан каждый вариант компонента, чтобы во вкладке story содержался код, который легко объясняет пример и может быть скопирован для использования.
https://timepad.myjetbrains.com/youtrack/issue/Dev-678/
> Dev-678 Доработать компонент dropdown

- src/components/divider/Divider.tsx
- src/components/divider/cdivider.less
[new] [S] - Добавил пропы и стили для компонента Divider
https://www.notion.so/timepaddev/hr-adivider-FC-1275f00554288036a551c26a6368468d?pvs=4
> Заменить тег hr с классом adivider на компонент из FC

- src/assets/css/fc-styles-bundle.less
- src/components/skeleton/Skeleton.stories.tsx
- src/components/skeleton/Skeleton.tsx
- src/components/skeleton/cskeleton.less
- src/components/skeleton/index.less
- src/components/skeleton/index.tsx
- src/index.tsx
В рамках задачи редизайна - [Редизайн 1 фронт](https://timepad.evateam.ru/desk/Task/BL-248?obj=Task:DEV-830#redizajn-glavnoj-lk-front-1-otobrazhenie-dannyh-o-tarife-i-vyruchke)
> Добавление компонента скелетон (с учетом паддингов children'ов)

- src/assets/svg/24/icon-arrow-left-24.svg
- src/assets/svg/24/icon-arrow-right-24.svg
Добавил две svg для раздела Сервисы главной ЛК
https://www.notion.so/timepaddev/Front-5-1275f005542880d48fe5fafe5c6cbcc3?pvs=4
> [Редизайн главной ЛК] Front 5. Сервисы

- src/components/form/Checkbox/Checkbox.stories.tsx
- src/components/form/Checkbox/Checkbox.tsx
- src/components/form/Checkbox/Checkbox.types.ts
[ref] [s] - добавил в пропс text, тип React.ReactNode и исправил disaeble чекбокса
https://timepad.evateam.ru/project/Kanban/KBB-000081?obj=Task:DEV-993#izmenit-tekst-v-forme-vhoda-registraczii
> Dev-993 Изменить текст в форме входа/регистрации

- src/services/hooks/useScript.tsx
1. [ref] В useScript добавлено условие для остановки и возможность указать id скрипта
https://timepad.evateam.ru/project/Task/DEV-1200#-otkaz-ot-gugl-analitiki--razrabotka
https://tracker.yandex.ru/DEV-1200
> DEV-1200 [Отказ от Гугл Аналитики] Разработка
